### ISSUE TITLE
Annoying Bot Owner bug.

### ISSUE THREAD

**Issue by GlitchHead** [DarkStorm652/DarkBot#41]
while botting a random server for fun some random person was able to do commands to the bots without being owner how is basically very easy you say the owners name and then a command ex Notch is the owner and a random player named popcorn can command bots by saying this in chat: "<popcorn> Notch !say HI" they bots will then say hi without notch doing a command and fooling the bots that Notch gave them a command.

**Comment by Unihedro** [comment]
I'm not able to reproduce this. Please add your environment specifications and the version of the bot you're using.

**Comment by GlitchHead** [comment]
i was using the latest development build and was botting a server the owner was McCrazy3122 some random person just said in chat McCrazy3122 !say hi! and the bots said hi.... the chat also did not have the < > things.

lel

**Comment by Unihedro** [comment]
"The chat also did not have the < > things" -> If your server chat environment does not tag messages with the player name correctly, the bot will not be able to handle them correctly, as that breaks the contract. The Minecraft multiplayer interface does not natively support knowing which users posted a chat message, and therefore neither does the bot. It only parses out the user name from the beginning of a line and expect it to work.

This issue is too localized and is not liable to be fixed. @DarkStorm652 Please close.
