### ISSUE TITLE
Is This Project Being Maintained Anymore?

### ISSUE THREAD

**Issue by pokeball99** [DarkStorm652/DarkBot#47]

**Comment by Unihedro** [comment]
no

**Comment by LefsFlare** [comment]
I don't like saying this but I'm the brother of the maintainer of this Git. He died as of a week ago when he contracted pneumonia, if any of you want to take over, drop me a message and I will pass along his private details, including the files he was working on before the illness hit.

**Comment by Unihedro** [comment]
@LefsFlare: I'm interested in taking over this project. I have extensive experience with software development, [a high reputation Stack Overflow profile](http://stackoverflow.com/users/3622940/unihedro), and [here's my CV.](https://careers.stackoverflow.com/unihedron) You can get in touch with my public email listed under my GitHub profile.

```
This response is obsolete.
```

**Comment by pokeball99** [comment]
Well, @LefsFlare,srry for your loss,but his legacy shall go on,rip @DarkStorm652

**Comment by DarkStorm652** [comment]
I'm still around to accept PRs and address issues, but I've found myself too strapped on time and motivation to do significant grunt work lately. Since starting school again I've had a lot going on and now I have finals approaching. I'll still make changes from time to time, especially during beaks, but I'm mostly hoping to phase this project out for [Blocknet](https://github.com/Axiometry/Blocknet), which will make actual AI, especially dealing with multiple bots collectively, much easier.

@Unihedro I'll send you a message
